import { SpeechItem } from '@/slices/agenda/Speech';

export const SATURDAY_AGENDA: SpeechItem[] = [
  {
    start: '',
    end: 'TBA',
    title: 'Kilka ciekawostek z (pre)historii informatyki',
    author: 'Jakub Juszczakiewicz',
    lang: ['pl'],
    description: ['Opowiem kilka ciekawostek z (pre)historii informatyki których skutki dalej kształtują rozwój tej branży.'],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Thermal Control in the Linux Kernel',
    author: 'Rafał Wysocki',
    lang: ['en'],
    description: ["The importance of thermal control has been growing since the outset of computing and it becomes critical as the sizes of systems get ever smaller and they are more and more constrained by their form factors. In contemporary systems, it is often impossible to run all of the components at full capacity at the same time and thermal control scenarios involve constraining performance and distributing power, so as to prevent the system from getting too hot while still allowing the users' expectations to be met. Many of these systems run the Linux kernel and it has to adequately respond to the thermal control challenges, which will be the focus of my talk. I will describe the Linux kernel's thermal control subsystem and explain how it works. I will also talk about the possible directions of its development in the future related to some interesting use cases that need to be addressed."],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Statistical Data Compression',
    author: 'Kamila Szewczyk',
    lang: ['en'],
    description: ['A brief dive into the world of data compression and the historical outline of popular data compression tools for Linux. A discussion on the reemergence of statistical data compression with modern tools such as bzip3, designed by the author of the talk.'],
    recording: '',
  },
  /*{
    start: '13:00',
    end: '14:00',
    title: 'Przerwa obiadowa',
  },*/
  {
    start: '',
    end: 'TBA',
    title: 'SELinux & Kubernetes bez doktoratu',
    author: 'Vladimir Mitiouchev',
    lang: ['pl'],
    description: ['Jak użyć SELinux do zabezpieczenia kontenerów w Kubernetes, bez robienia z niego doktoratu. W prezentacji nie ma audit2allow, ani SELINUX=disabled, za to jest live demo.'],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'eBPF w Linuxie: Badanie wydajności i nie tylko',
    author: 'Filip Dorosz',
    lang: ['pl'],
    description: ["Co to właściwie jest eBPF i czemu warto go używać? Jak używać eBPF? Czy można tak zobaczyć coś użytecznego? Na te i wiele więcej pytań padną odpowiedzi w trakcie ekscytującej(a jakże!) prezentacji która pokaże jak można badać wydajność (i nie tylko!) systemu Linux."],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Low cost, silicon based semiconductor manufacturing at home',
    author: 'Patryk Wlazłyń',
    lang: ['pl'],
    description: ["I'll go through a small lab that I have built with the team for silicon based semiconductor manufacturing powered with open source software, that allowed us to create resistors, diodes, solar cells and NMOS transistors."],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Demon w trampkach, czyli pełne zanurzenie w ekosystem FreeBSD',
    author: 'Mateusz Piotrowski',
    lang: ['pl'],
    description: ["FreeBSD jest systemem operacyjnym wywodzącym się w prostej linii z legendarnego systemu Unix i jest kontynuacją projektu BSD (pierwszego otwartego systemu operacyjnego w historii). W ciągu ponad 30 lat swojego istnienia projekt FreeBSD nie tylko rozwiną się technologicznie, ale również wypracował kulturę, procesy i struktury, które scalają społeczność i pozwalają na sprawne funkcjonowanie projektu tworzonego przez tysiące osób z całego świata.",
    "",
    "Podczas prelekcji poznamy odpowiedzi na kilka podstawowych pytań ze świata FreeBSD. Kto jest kim i jak zostać kimś? Co jest czym i jak się czymś zająć? Innymi słowy, skupimy się na takich rzeczach, jak:",
    "",
    "1. Struktury i dynamiki rządzące dużym projektem otwartego oprogramowania jak FreeBSD",
    "",
    "2. Znane wdrożenia FreeBSD w branży i uczestnictwo dużych graczy w ekosystemie",
    "",
    "3. Zalety systemu FreeBSD, ale również wyzwaniach, z którymi mierzy się teraz społeczność",
    "",
    "4. Pierwsze kroki w otwartym oprogramowaniu, które pozwolą Ci zacząć kontrybuować do dużego systemu operacyjnego (używanego przez co najmniej dwie litery z akronimu MANGA)",
    "",
    "",
    "https://www.freebsd.org/",
    "https://freebsdfoundation.org/",
    "https://www.facesofopensource.com/bsd/"],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Multimedia in Fedora: the Past, the Present and the Future',
    author: 'Dominik Mierzejewski',
    lang: ['pl'],
    description: ['Historically, Fedora has been the only top ten Linux distribution missing a significant chunk of multimedia software mostly due to FFmpeg being excluded from the distribution for legal reasons. With the introduction of a limited build of FFmpeg in February 2022, that changed. This talk will cover the history of multimedia software in Fedora and its current status. I will introduce the Multimedia Special Interest Group and talk about plans for the future.'],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Free/Open software w prywatnym użyciu - czy da się nie będąc adminem?',
    author: 'Piotr Pyciński',
    lang: ['pl'],
    description: ["Postaram się przeglądnąć najpopularniejsze wolne / otwarte oprogramowanie, które można wykorzystać w domu. Spróbujemy zmierzyć się z jego instalacją przez osoby nie posiadające wyszkolenia informatycznego.",
    "",
    "Dodatkowo przytoczę 5-7 lat osobistych doświadczeń z hostowaniem własnej poczty oraz usług domowych. Zastanowimy się czy wolne / otwarte oprogramowanie jest przygotowane na osoby nie techniczne."],
    recording: '',
  },
  {
    start: '',
    end: 'TBA',
    title: 'Performance analysis and benchmarking on Linux',
    author: 'Krzysztof Biegański',
    lang: ['pl'],
    description: ['This presentation will provide an overview of the world of performance analysis and benchmarking on Linux, starting with how to correctly assess optimization needs. We’ll also explore open source tools such as perf that let us identify bottlenecks and similar issues, as well as talk about reducing noise in our measurements to ensure accurate and reliable performance assessment.'],
    recording: '',
  },
];

export const SUNDAY_AGENDA: SpeechItem[] = [
  {
    start: '10:00',
    end: '10:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '11:00',
    end: '11:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '12:00',
    end: '12:50',
    title: '',
    lang: ['pl'],
    author: ``,
    description: [''],
    recording: '',
  },
  {
    start: '13:00',
    end: '14:00',
    title: 'Przerwa obiadowa',
  },
  {
    start: '14:00',
    end: '14:50',
    title: '',
    author: ``,
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '15:00',
    end: '15:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'Lightning talks',
    lang: ['en', 'pl'],
    description: [
      'Chciałbyś poruszyć ważny dla Ciebie temat, lub przekazać myśl do społeczności Open Source? Przyjdź i zrób to!',
    ],
    recording: '',
  },
];
