import { SpeechItem } from '@/slices/agenda/Speech';

export const SATURDAY_AGENDA: SpeechItem[] = [
  {
    start: '10:00',
    end: '10:50',
    title: '',
    author: '',
    lang: ['en'],
    description: [''],
    recording: '',
  },
  {
    start: '11:00',
    end: '11:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '12:00',
    end: '12:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '13:00',
    end: '14:00',
    title: 'Przerwa obiadowa',
  },
  {
    start: '14:00',
    end: '14:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '15:00',
    end: '15:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '16:00',
    end: '16:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '17:00',
    end: '17:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
];

export const SUNDAY_AGENDA: SpeechItem[] = [
  {
    start: '10:00',
    end: '10:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '11:00',
    end: '11:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '12:00',
    end: '12:50',
    title: '',
    lang: ['pl'],
    author: ``,
    description: [''],
    recording: '',
  },
  {
    start: '13:00',
    end: '14:00',
    title: 'Przerwa obiadowa',
  },
  {
    start: '14:00',
    end: '14:50',
    title: '',
    author: ``,
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '15:00',
    end: '15:50',
    title: '',
    author: '',
    lang: ['pl'],
    description: [''],
    recording: '',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'Lightning talks',
    lang: ['en', 'pl'],
    description: [
      'Chciałbyś poruszyć ważny dla Ciebie temat, lub przekazać myśl do społeczności Open Source? Przyjdź i zrób to!',
    ],
    recording: '',
  },
];
